title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: nighthawkcoders
baseurl: ""
remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: pages-themes/terminal@v0.7.1
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: 
plugins:
- jekyll-remote-theme
future: true
